### PR TITLE
Add integration testing with james

### PR DESCRIPTION
**Pull request by remk**

### CODE REVIEW

**Comment by remk** [comment]
This PR  add integration testing with James in addition to the tests done with Cyrus

put in evidence that : 
 - the james in memory implementation is faulty. (a commit fix it, but is it normal to do so ?)
-  the ImapSimpleScenario will fail as the imap nio lib fail to parse james response from FETCH commands with BODY[...]. 
i may remove the failing FETCH from the tests...

I think the test on james is good but different problems might make this PR unmergeable.
What do you think is the best way to handle this ?

**Comment by rouazana** [comment]
let's merge the working case, and open issues for the failing cases, we will fix them later.
Thus we will be able to launch some scenario before having everything working perfectly

**Comment by remk** [comment]
The issues this PR demonstrates : 
https://ci.linagora.com/linagora/lgs/openpaas/james/issues/1242
https://ci.linagora.com/linagora/lgs/openpaas/james/issues/1243

**Review by rouazana — APPROVED** [review]

**Comment by remk** [comment]
All the precedent problems have been resolved.
However there is a difference in behavior between cyrus and james.
When fetching the last messages on an empty mailbox, 
Cyrus will return a `NO` answer, whereas James will return a ` BAD FETCH failed. Invalid messageset.` answer.

Can we accept both in the test or is one behavior not desirable ?

**Comment by Arsnael** [comment]
> When fetching the last messages on an empty mailbox,
> Cyrus will return a NO answer, whereas James will return a BAD FETCH failed. Invalid messageset. answer.
> 
> Can we accept both in the test or is one behavior not desirable ?

Did we check if there is anything in the RFC related to that case? 

BTW from Travis-CI:
```
[error] Failed tests:
[error] 	com.linagora.gatling.imap.scenario.it.ImapSimpleScenarioJamesIT
[error] 	com.linagora.gatling.imap.scenario.it.ImapAuthenticationScenarioJamesIT
```

**Comment by rouazana** [comment]
> Did we check if there is anything in the RFC related to that case?

Not clear for me:
https://tools.ietf.org/html/rfc3501#page-54
```
               NO - fetch error: can't fetch that data
               BAD - command unknown or arguments invalid
```

**Comment by Arsnael** [comment]
Well the RFC seems clear for the NO.

**Comment by remk** [comment]
The ImapAuthenticationScenario fails too on a fetch with James.

By simplifying it we can see that, on a mailbox with one message.
If i try to fetch the message 1 and 2.

Cyrus will return the message first message without complaining.

James will declare the request as bad and will return no message.

It is still not clear for me which behavior is the closest to the RFC.

Maybe, we should simplify the gatling integration test to fetch only existing messages and create an issue in James (or cyrus)

**Comment by Arsnael** [comment]
> By simplifying it we can see that, on a mailbox with one message.
> If i try to fetch the message 1 and 2.

> James will declare the request as bad and will return no message.

Yes that is exactly why I had to reduce the end fetch on one IMAP scenario before on the new provisionning, as it has twice less mails than the previous one (so was constantly failing doing a fetch)

**Comment by Arsnael** [comment]
I'm not sure either what is the closest behavior to the RFC. However, I would say that the Cyrus way is more user-friendly. It's more like I put a limit but if we don't reach it it's fine kinda logic. While James is very strict in the fact that if the fetch limit is higher than your number of messages, it fails.

I believe James behavior is too strict TBH

**Comment by remk** [comment]
> I'm not sure either what is the closest behavior to the RFC. However, I would say that the Cyrus way is more user-friendly. It's more like I put a limit but if we don't reach it it's fine kinda logic. While James is very strict in the fact that if the fetch limit is higher than your number of messages, it fails.
> 
> I believe James behavior is too strict with fetch TBH

This will be done in  https://github.com/linagora/james-project/issues/4215

**Review by rouazana — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Pull request merged**
