### PR TITLE
Fix README about ports and host parametrization

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by rouazana** [comment]
```
[error] /home/travis/build/linagora/gatling-imap/src/main/scala-2.12/com/linagora/gatling/imap/protocol/ImapProtocolBuilder.scala:4:28: value envOrElse is not a member of scala.sys.SystemProperties
[error]   val HOSTNAME = sys.props.envOrElse("TARGET_HOSTNAME", "localhost")
[error]                            ^
[error] /home/travis/build/linagora/gatling-imap/src/main/scala-2.12/com/linagora/gatling/imap/protocol/ImapProtocolBuilder.scala:5:24: value envOrElse is not a member of scala.sys.SystemProperties
[error]   val PORT = sys.props.envOrElse("IMAP_PORT", "143").toInt
[error]                        ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 40 s, completed Jun 3, 2019 3:05:34 PM
```

**Comment by remk** [comment]
scala.util.Properties.envOrElse  ?

**Comment by rouazana** [comment]
I fear the fix is not what @blackheaven is expecting :)

**Comment by blackheaven** [comment]
@rouazana I think it does not work, I had troubles

**Pull request merged**
